[package]
name = "aoc2023"
edition = "2021"

[[bin]]
name = "day08"
path = "08/main.rs"

[dependencies]
regex = "1.10.2"

[[bin]]
name = "day09"
path = "09/main.rs"

[[bin]]
name = "day10"
path = "10/main.rs"

[[bin]]
name = "day11"
path = "11/main.rs"

[[bin]]
name = "day12"
path = "12/main.rs"
